GET http://localhost:4000/v1/healthcheck HTTP/1.1

### User signup. Requests verificaiton token.
POST http://localhost:4000/v1/tokens/verification/registration HTTP/1.1
content-type: application/json

{
    "email": "johndoe@example.com"
}

### Use verificaiton token to create an account
POST http://localhost:4000/v1/users HTTP/1.1
content-type: application/json

{
    "email": "johndoe@example.com",
    "password": "helloworld",
    "token": "BV5FCUSQYBD5DE2XFGCWP72MSI"
}

### Request authentication token in exchange for credentials
POST http://localhost:4000/v1/tokens/authentication HTTP/1.1
content-type: application/json

{
    "email": "johndoe@example.com",
    "password": "helloworld"
}

### Use auth token to get user information
GET http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer MBPIW4MBKBUM57RPEMOJ6I27JE

### Request a verification token to change email
POST http://localhost:4000/v1/tokens/verification/email-change HTTP/1.1
Authorization: Bearer MBPIW4MBKBUM57RPEMOJ6I27JE
content-type: application/json

{
    "email": "dames@domain.org"
}

### Update user with new email address
PUT http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer MBPIW4MBKBUM57RPEMOJ6I27JE
content-type: application/json

{
    "email": "dames@domain.org",
    "token": "PBKD6WANZYM6OBVIW6D4ZN5ZHM"
}

### Request a password reset
POST http://localhost:4000/v1/tokens/verification/email-change HTTP/1.1
Authorization: Bearer MBPIW4MBKBUM57RPEMOJ6I27JE
content-type: application/json

{
    "email": "dames@domain.org"
}
